-keepattributes *Annotation*
-keepattributes Signature
-keepattributes EnclosingMethod
-keep class * extends androidx.room.RoomDatabase
-keep @androidx.room.Entity class *
-dontwarn androidx.room.paging.**
-keep class kotlin.Metadata { *; }
